(in-package #:xlsxwriter)

(defctype lxw-row :int32)
(defctype lxw-col :int32)
(defctype lxw-workbook :pointer)
(defctype lxw-worksheet :pointer)
(defctype lxw-format :pointer)
(defctype lxw-color :int32)

(defcenum lxw-error
  :LXW-NO-ERROR
  :LXW-ERROR-MEMORY-MALLOC-FAILED
  :LXW-ERROR-CREATING-XLSX-FILE
  :LXW-ERROR-CREATING-TMPFILE
  :LXW-ERROR-READING-TMPFILE
  :LXW-ERROR-ZIP-FILE-OPERATION
  :LXW-ERROR-ZIP-PARAMETER-ERROR
  :LXW-ERROR-ZIP-BAD-ZIP-FILE
  :LXW-ERROR-ZIP-INTERNAL-ERROR
  :LXW-ERROR-ZIP-FILE-ADD
  :LXW-ERROR-ZIP-CLOSE
  :LXW-ERROR-NULL-PARAMETER-IGNORED
  :LXW-ERROR-PARAMETER-VALIDATION
  :LXW-ERROR-SHEETNAME-LENGTH-EXCEEDED
  :LXW-ERROR-INVALID-SHEETNAME-CHARACTER
  :LXW-ERROR-SHEETNAME-START-END-APOSTROPHE
  :LXW-ERROR-SHEETNAME-ALREADY-USED
  :LXW-ERROR-SHEETNAME-RESERVED
  :LXW-ERROR-32-STRING-LENGTH-EXCEEDED
  :LXW-ERROR-128-STRING-LENGTH-EXCEEDED
  :LXW-ERROR-255-STRING-LENGTH-EXCEEDED
  :LXW-ERROR-MAX-STRING-LENGTH-EXCEEDED
  :LXW-ERROR-SHARED-STRING-INDEX-NOT-FOUND
  :LXW-ERROR-WORKSHEET-INDEX-OUT-OF-RANGE
  :LXW-ERROR-WORKSHEET-MAX-NUMBER-URLS-EXCEEDED
  :LXW-ERROR-IMAGE-DIMENSIONS)

(defcenum lxw-format-alignments
  :LXW-ALIGN-NONE
  :LXW-ALIGN-LEFT
  :LXW-ALIGN-CENTER
  :LXW-ALIGN-RIGHT
  :LXW-ALIGN-FILL
  :LXW-ALIGN-JUSTIFY
  :LXW-ALIGN-CENTER-ACROSS
  :LXW-ALIGN-DISTRIBUTED
  :LXW-ALIGN-VERTICAL-TOP
  :LXW-ALIGN-VERTICAL-BOTTOM
  :LXW-ALIGN-VERTICAL-CENTER
  :LXW-ALIGN-VERTICAL-JUSTIFY
  :LXW-ALIGN-VERTICAL_DISTRIBUTED)

(defcenum lxw-format-patterns
  :LXW-PATTERN-NONE
  :LXW-PATTERN-SOLID
  :LXW-PATTERN-MEDIUM_GRAY
  :LXW-PATTERN-DARK_GRAY
  :LXW-PATTERN-LIGHT_GRAY
  :LXW-PATTERN-DARK_HORIZONTAL
  :LXW-PATTERN-DARK_VERTICAL
  :LXW-PATTERN-DARK_DOWN
  :LXW-PATTERN-DARK_UP
  :LXW-PATTERN-DARK_GRID
  :LXW-PATTERN-DARK_TRELLIS
  :LXW-PATTERN-LIGHT_HORIZONTAL
  :LXW-PATTERN-LIGHT_VERTICAL
  :LXW-PATTERN-LIGHT_DOWN
  :LXW-PATTERN-LIGHT_UPc
  :LXW-PATTERN-LIGHT_GRID
  :LXW-PATTERN-LIGHT_TRELLIS
  :LXW-PATTERN-GRAY_125
  :LXW-PATTERN-GRAY_0625)

(defcenum lxw-format-borders
  :LXW-BORDER-NONE
  :LXW-BORDER-THIN
  :LXW-BORDER-MEDIUM
  :LXW-BORDER-DASHED
  :LXW-BORDER-DOTTED
  :LXW-BORDER-THICK
  :LXW-BORDER-DOUBLE
  :LXW-BORDER-HAIR
  :LXW-BORDER-MEDIUM_DASHED
  :LXW-BORDER-DASH_DOT
  :LXW-BORDER-MEDIUM_DASH_DOT
  :LXW-BORDER-DASH_DOT_DOT
  :LXW-BORDER-MEDIUM_DASH_DOT_DOT
  :LXW-BORDER-SLANT_DASH_DOT)


;;; Constants

(defconstant LXW-COLOR-BLACK 	  #x1000000)
(defconstant LXW-COLOR-BLUE 	  #x0000FF)
(defconstant LXW-COLOR-BROWN 	  #x800000)
(defconstant LXW-COLOR-CYAN 	  #x00FFFF)
(defconstant LXW-COLOR-GRAY 	  #x808080)
(defconstant LXW-COLOR-GREEN 	  #x008000)
(defconstant LXW-COLOR-LIME 	  #x00FF00)
(defconstant LXW-COLOR-MAGENTA 	#xFF00FF)
(defconstant LXW-COLOR-NAVY 	  #x000080)
(defconstant LXW-COLOR-ORANGE 	#xFF6600)
(defconstant LXW-COLOR-PINK 	  #xFF00FF)
(defconstant LXW-COLOR-PURPLE 	#x800080)
(defconstant LXW-COLOR-RED 	    #xFF0000)
(defconstant LXW-COLOR-SILVER 	#xC0C0C0)
(defconstant LXW-COLOR-WHITE 	  #xFFFFFF)
(defconstant LXW-COLOR-YELLOW 	#xFFFF00)

